### ISSUE TITLE
Onboarding credentials showing loading spinner without credentials

### ISSUE THREAD

**Issue by TimoGlastra** [animo/animo-demo#26]
Lately when going through the onboarding flow, sometimes the issuance of the started credentials shows the following page. When resetting the dashboard and starting over it is often resolved, but I've had occurrences where it will happen twice in a row.

Not sure what is going on here. No errors are logged in the browser console.

![image](https://user-images.githubusercontent.com/23165168/150795631-38952521-3037-4e84-a884-2d64f95426a8.png)

@janrtvld any idea what is happening here?

**Comment by janrtvld** [comment]
This is probably because the credential issue request is rejected or still pending (for some reason). I've made it so that you can't continue, but when the request is rejected there's no error handling in place. The user can issue the credentials again by pressing `i didn't receive anything`, but this should be handled differently.

What wallet are you using? I've had this issue with the Trinsic wallet sometimes, but never with Lissi.

Request is not send. When reloading the request is send but onboarding is reset?

**Comment by janrtvld** [comment]
Closing this as i've added error handling a few months back and this should be solved.
